### PR TITLE
WFESO-4474 Move to Github Actions from TravisCI

### PR DESCRIPTION
**Pull request by JMoravec**

### CODE REVIEW

**Comment by laullon** [comment]
Can we add Java 17 ?

**Comment by laullon** [comment]
Can we add Java 17 ?

**Comment by JMoravec** [comment]
@laullon Currently the build fails with 16 and 17, since the pom requires specific versions:
https://github.com/wavefrontHQ/wavefront-proxy/blob/master/proxy/pom.xml#L82

https://github.com/wavefrontHQ/wavefront-proxy/runs/5517788559?check_suite_focus=true
https://github.com/wavefrontHQ/wavefront-proxy/runs/5517788605?check_suite_focus=true

```
Warning:  Rule 0: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
Detected JDK Version: 16.0.2 is not in the allowed range [1.8,12).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.494 s
[INFO] Finished at: 2022-03-11T22:32:54Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (enforce-java) on project proxy: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

**Comment by laullon** [comment]
I've change the pom.xml, can we try now?

**Comment by laullon** [comment]
It's possible to mark java version as optional ? That was possible on Travis CI.
Can we make 11 mandatory and 16 and 17 optional ?

**Comment by JMoravec** [comment]
@laullon Currently all the Github Action builds are optional, as I believe that's a setting on the repo itself. Whoever has access to those settings can remove the required Travis CI required build on Github, and then add the Java 11 as required before being allowed to merge.

**Review by joannak-vmware — APPROVED** [review]

**Review by laullon — APPROVED** [review]

**Pull request merged**
