### PR TITLE
MONIT-34326: Remove preprocessor rules returned from server

### PR DESCRIPTION
**Pull request by joannak-vmware**

### CODE REVIEW

**Review by laullon — APPROVED** [review]
LGTM

**Review by formanojhr — COMMENTED** [review]
LGTM

**Review by amitw-vmware — APPROVED** [review]
lgtm

**Comment by alchen1218** [comment]
Verifed. I built/ran a local docker image of this branch and checked the logs and do not see: `java.lang.RuntimeException: Can't parse preprocessor configuration `

**Pull request merged**
