### PR TITLE
proxy-pom.xml: skip format-code plugin

### PR DESCRIPTION
**Pull request by prashant1221**
On the released tags tarball 11.4 and 12.0, `mvn -f proxy clean install -DskipTest` fails to execute format-code on project proxy because it expects the source to be git repository. 

> [ERROR] Failed to execute goal com.cosium.code:git-code-format-maven-plugin:3.3:format-code (format-code) on project proxy: Execution format-code of goal com.cosium.code:git-code-format-maven-plugin:3.3:format-code failed: One of setGitDir or setWorkTree must be called. -> [Help 1]

Added the PR to skip this in proxy/pom.xml while doing mvn install. 
 `mvn -f proxy clean install -DskipTests -DskipFormatCode` skips the format code for a released tarball.

### CODE REVIEW

**Comment by sshedi** [comment]
This fix helps while building wavefront rpm from released source tarball, else we need to do git init after extracting the tagged tarball; since it's tagged code, is there any advantage in running format code on it? By released code I assume that code is already formatted.

**Comment by laullon** [comment]
Hi, @prashant1221 and @sshedi Can you please ping me on slack ?

**Comment by sshedi** [comment]
Hi @laullon , can you please take these changes?

**Comment by laullon** [comment]
LGTM, @sshedi can you add a note on the `readme.md` file about `-DskipFormatCode`, then I'll merge it to `dev` branch and `master`

**Comment by sshedi** [comment]
> LGTM, @sshedi can you add a note on the `readme.md` file about `-DskipFormatCode`, then I'll merge it to `dev` branch and `master`

Sure, thanks.

**Review by laullon — APPROVED** [review]
LGTM

**Comment by sshedi** [comment]
Thanks @laullon for your time and patience.

**Pull request merged**
